
import { v4 as uuidv4 } from 'uuid';
const shipmentsData = [
    {
        id: uuidv4(),
        status: 'arrival',
        product: 'Product A',
        destination: 'Location X',
        eta: '2023-10-20',
        departureDate: '2023-10-25',
        quantity: 100,
      },
      {
        id: uuidv4(),
        status: 'store',
        product: 'Product B',
        destination: 'Location Y',
        eta: '2023-10-22',
        departureDate: '2023-10-28',
        quantity: 50,
      },
      {
        id: uuidv4(),
        status: 'dispatch',
        product: 'Product C',
        destination: 'Location Z',
        eta: '2023-10-25',
        departureDate: '2023-10-27',
        quantity: 75,
      },
      {
        id: uuidv4(),
        status: 'arrival',
        product: 'Product D',
        destination: 'Location W',
        eta: '2023-10-21',
        departureDate: '2023-10-26',
        quantity: 60,
      },
      {
        id: uuidv4(),
        status: 'store',
        product: 'Product E',
        destination: 'Location V',
        eta: '2023-10-23',
        departureDate: '2023-10-29',
        quantity: 70,
      },
      {
        id: uuidv4(),
        status: 'dispatch',
        product: 'Product F',
        destination: 'Location U',
        eta: '2023-10-26',
        departureDate: '2023-10-28',
        quantity: 45,
      },
      {
        id: uuidv4(),
        status: 'arrival',
        product: 'Product G',
        destination: 'Location T',
        eta: '2023-10-24',
        departureDate: '2023-10-26',
        quantity: 90,
      },
      {
        id: uuidv4(),
        status: 'store',
        product: 'Product H',
        destination: 'Location S',
        eta: '2023-10-27',
        departureDate: '2023-10-29',
        quantity: 40,
      },
      {
        id: uuidv4(),
        status: 'dispatch',
        product: 'Product I',
        destination: 'Location R',
        eta: '2023-10-29',
        departureDate: '2023-10-30',
        quantity: 30,
      },
      {
        id: uuidv4(),
        status: 'arrival',
        product: 'Product J',
        destination: 'Location Q',
        eta: '2023-10-25',
        departureDate: '2023-10-28',
        quantity: 80,
      },
      {
        id: uuidv4(),
        status: 'store',
        product: 'Product K',
        destination: 'Location P',
        eta: '2023-10-27',
        departureDate: '2023-10-30',
        quantity: 55,
      },
      {
        id: uuidv4(),
        status: 'dispatch',
        product: 'Product L',
        destination: 'Location O',
        eta: '2023-10-30',
        departureDate: '2023-11-01',
        quantity: 65,
      },
      {
        id: uuidv4(),
        status: 'arrival',
        product: 'Product M',
        destination: 'Location N',
        eta: '2023-10-28',
        departureDate: '2023-10-30',
        quantity: 70,
      },
      {
        id: uuidv4(),
        status: 'store',
        product: 'Product N',
        destination: 'Location M',
        eta: '2023-10-31',
        departureDate: '2023-11-02',
        quantity: 45,
      },
    // Add more shipment data here
  ];
  
  export default shipmentsData;
  